language: ruby
bundler_args: --without guard 
script: "bundle exec rake ci" 
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode 
  - jruby-19mode 
  - rbx-18mode
  - rbx-19mode
matrix:
  allowed_failures:
    - rvm: rbx-18mode # rbx in 18mode does not have Object.public_send?
notifications:
  email:
    - mbj@seonic.net
